#!/usr/bin/env bash

lsd_control=~/.lsd-control
if [[ -f "${lsd_control}" ]]; then
    source "${lsd_control}"
else
    touch ${lsd_control}
    echo -ne "lsd=true" > ${lsd_control}
    lsd=true
fi


if [[ ${TERM} = "linux" ]]; then
    exit 0
fi


set +e
unalias ls > /dev/null 2>&1


case ${lsd} in
    true) alias ls='lsd';;
    false) alias ls='ls';;
    *) :;;
esac